// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqox5x5roK0ysm-wsyoJUHuBFO_-amK14',
    appId: '1:490301747901:web:34b24ecb7c3c6b93f83dd4',
    messagingSenderId: '490301747901',
    projectId: 'nshiva-cmsc5303-mobileapps',
    authDomain: 'nshiva-cmsc5303-mobileapps.firebaseapp.com',
    storageBucket: 'nshiva-cmsc5303-mobileapps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxjWqJR0LjbN9sPjAzVIzVo5BIZ6A5hOE',
    appId: '1:490301747901:android:9a5d473d53b82ab0f83dd4',
    messagingSenderId: '490301747901',
    projectId: 'nshiva-cmsc5303-mobileapps',
    storageBucket: 'nshiva-cmsc5303-mobileapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADbHYsP44FJGghGbX9dwSiLD9OgnPXW1E',
    appId: '1:490301747901:ios:faec3800fd417df4f83dd4',
    messagingSenderId: '490301747901',
    projectId: 'nshiva-cmsc5303-mobileapps',
    storageBucket: 'nshiva-cmsc5303-mobileapps.appspot.com',
    iosClientId: '490301747901-hgtf9dqv3kddupl1j5lipouvto6m0t9h.apps.googleusercontent.com',
    iosBundleId: 'edu.uco.nshiva.cmsc5303.lesson4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADbHYsP44FJGghGbX9dwSiLD9OgnPXW1E',
    appId: '1:490301747901:ios:faec3800fd417df4f83dd4',
    messagingSenderId: '490301747901',
    projectId: 'nshiva-cmsc5303-mobileapps',
    storageBucket: 'nshiva-cmsc5303-mobileapps.appspot.com',
    iosClientId: '490301747901-hgtf9dqv3kddupl1j5lipouvto6m0t9h.apps.googleusercontent.com',
    iosBundleId: 'edu.uco.nshiva.cmsc5303.lesson4',
  );
}
